import React from "react";import{createRoot}from"react-dom/client";import{motion}from"motion/react";import{ArrowUpRight,ChevronDown,Instagram,MapPin,Menu,X}from"lucide-react";import{gsap}from"gsap";import{ScrollTrigger}from"gsap/ScrollTrigger";import"./styles.css";
gsap.registerPlugin(ScrollTrigger);
const IMG={hero:"https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=2200&q=88",lift:"https://images.unsplash.com/photo-1581009146145-b5ef050c2e1a?auto=format&fit=crop&w=1600&q=88",coach:"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1400&q=88",run:"https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1400&q=88",earth:"https://images-assets.nasa.gov/image/EPIC_1B_20150716063828/EPIC_1B_20150716063828~orig.jpg"};
const plans=[["FORGE","₹1,499","/ month","Open gym • All equipment • Locker"],["KINGDOM","₹2,499","/ month","Unlimited access • Classes • Sauna"],["ELITE","₹4,999","/ month","Personal coaching • Nutrition • 24/7 access"]];
const quotes=["DISCIPLINE OUTLASTS MOTIVATION.","NO ONE IS COMING. BUILD YOURSELF.","THE WEIGHT DOESN’T CARE ABOUT YOUR EXCUSES.","EARN YOUR STRENGTH.","BECOME HARD TO BREAK."];
function App(){const[menu,setMenu]=React.useState(false);React.useEffect(()=>{gsap.utils.toArray(".reveal").forEach((el)=>gsap.fromTo(el,{y:70,opacity:0},{y:0,opacity:1,duration:1,ease:"power3.out",scrollTrigger:{trigger:el,start:"top 88%"}}));gsap.to(".earth",{rotate:360,duration:90,repeat:-1,ease:"none"});return()=>ScrollTrigger.getAll().forEach(t=>t.kill())},[]);
return <div className="app"><div className="grain"/><nav><a className="logo" href="#top">K<span>•</span>NGDOM</a><div className={"links "+(menu?"open":"")}><a href="#story" onClick={()=>setMenu(false)}>Story</a><a href="#training" onClick={()=>setMenu(false)}>Training</a><a href="#membership" onClick={()=>setMenu(false)}>Membership</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a></div><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><a className="navcta" href="#membership">JOIN THE KINGDOM <ArrowUpRight size={15}/></a></nav>
<main id="top"><section className="hero"><div className="hero-bg" style={{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.88),rgba(0,0,0,.3)),url(${IMG.hero})`}}/><div className="hero-copy"><p className="eyebrow">EST. 2026 • BIHAR, INDIA</p><h1>BUILD<br/><i>YOUR</i><br/>KINGDOM.</h1><p className="lead">A performance-first training house for people who refuse ordinary.</p><div className="hero-actions"><a className="button primary" href="#membership">START TRAINING <ArrowUpRight/></a><a className="button ghost" href="#story">EXPLORE <ChevronDown/></a></div></div><div className="hero-side">01 / 05<br/><span>STRENGTH<br/>MOBILITY<br/>MINDSET</span></div><div className="scroll">SCROLL TO BUILD <span/></div></section>
<section className="manifesto" id="story"><div className="manifesto-left reveal"><p className="eyebrow">THE KINGDOM CODE</p><h2>WE DON'T<br/><em>CHASE</em><br/>MOTIVATION.</h2></div><div className="manifesto-right reveal"><p>We engineer the environment where discipline becomes automatic. Heavy iron. Sharp coaching. Better recovery. No distractions.</p><div className="statgrid"><div><strong>12K+</strong><span>WORKOUTS LOGGED</span></div><div><strong>38</strong><span>WEEKLY CLASSES</span></div><div><strong>24/7</strong><span>ACCESS</span></div><div><strong>01</strong><span>STANDARD</span></div></div></div></section>
<section className="earth-section"><div className="earth-wrap"><img className="earth" src={IMG.earth} alt="Earth photographed by NASA"/><div className="orbit o1"/><div className="orbit o2"/></div><div className="earth-copy reveal"><p className="eyebrow">BIGGER THAN A GYM</p><h2>YOUR WORLD<br/>GETS <span>SMALLER</span><br/>WHEN YOU TRAIN.</h2><p>Every rep expands your idea of what is possible. Train here, then take that strength everywhere.</p></div></section>
<section className="training" id="training"><div className="section-head reveal"><p className="eyebrow">THE METHOD</p><h2>TRAIN WITH<br/><em>INTENT.</em></h2></div><div className="cards">{[[IMG.lift,"01","STRENGTH","Build raw force with progressive overload and serious equipment."],[IMG.coach,"02","PERFORMANCE","Move better. Recover faster. Perform when it matters."],[IMG.run,"03","CONDITIONING","Engine work that turns effort into endurance."]].map(([im,n,t,d])=><motion.article className="train-card" whileHover={{y:-12}} key={t}><img src={im} alt={t}/><div className="card-overlay"/><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></motion.article>)}</div></section>
<section className="quotes"><div className="quote-track">{quotes.concat(quotes).map((q,i)=><span key={i}>{q}<b>✦</b></span>)}</div></section>
<section className="membership" id="membership"><div className="section-head reveal"><p className="eyebrow">CHOOSE YOUR STANDARD</p><h2>ENTER THE<br/><em>KINGDOM.</em></h2></div><div className="plans">{plans.map(([n,p,u,d],i)=><motion.article whileHover={{scale:1.02}} className={"plan "+(i===1?"featured":"")} key={n}><div className="plan-top"><span>0{i+1}</span>{i===1&&<b>MOST POPULAR</b>}</div><h3>{n}</h3><div className="price">{p}<small>{u}</small></div><p>{d}</p><a href="#contact">CLAIM YOUR PLACE <ArrowUpRight/></a></motion.article>)}</div></section>
<section className="cta" id="contact"><div className="cta-bg" style={{backgroundImage:`linear-gradient(rgba(0,0,0,.45),rgba(0,0,0,.8)),url(${IMG.hero})`}}/><div className="cta-content reveal"><p className="eyebrow">NO EXCUSES. JUST WORK.</p><h2>READY TO<br/><em>BUILD?</em></h2><a className="button primary" href="tel:+919999999999">BOOK A FREE TOUR <ArrowUpRight/></a></div></section></main>
<footer><div><a className="logo">K<span>•</span>NGDOM</a><p>Strength is built, not found.</p></div><div><span>LOCATION</span><p><MapPin size={14}/> Bettiah, Bihar, India</p></div><div><span>FOLLOW</span><p><Instagram size={14}/> @kingdom.gym</p></div><div><span>HOURS</span><p>OPEN 24 / 7</p></div></footer></div>}
createRoot(document.getElementById("root")).render(<App/>);